version: 2

aliases:
  - &restore-cache
    restore_cache:
      key: dependency-cache-{{ checksum "package.json" }}
  - &install-deps
    run:
      name: Install dependencies
      command: npm ci
  - &build-packages
    run:
      name: Build
      command: npm run build
  - &run-unit-tests
    run:
      name: Test
      command: npm run test

unit-tests-template: &unit-tests-template
  working_directory: ~/nest
  steps:
    - checkout
    - *restore-cache
    - *install-deps
    - *build-packages
    - *run-unit-tests

jobs:
  build:
    working_directory: ~/nest
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run:
          name: Update NPM version
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: npm ci
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Build
          command: npm run build

  test_node_14:
    working_directory: ~/nest
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - *restore-cache
      - *install-deps
      - *build-packages
      - *run-unit-tests
#      - run:
#          name: Collect coverage
#          command: npm run coverage
#      - store_artifacts:
#          path: coverage

  test_node_12:
    <<: *unit-tests-template
    docker:
      - image: circleci/node:12

  test_node_10:
    <<: *unit-tests-template
    docker:
      - image: circleci/node:10

  lint:
    working_directory: ~/nest
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - *restore-cache
      - *install-deps
      - run:
          name: Lint
          command: npm run lint
#      - run:
#          name: Lint commit
#          command: ./node_modules/.bin/commitlint-circle -c .commitlintrc.json

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - test_node_14:
          requires:
            - build
      - test_node_12:
          requires:
            - build
      - test_node_10:
          requires:
            - build
      - lint:
          requires:
            - build
